---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: f2

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - flagValue: true
    group:
      id: fb482a73-cf58-4e48-be55-e3161138e488
