---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: TG1

description: 

conditions:
  allOf:
    - property:
        name: stringProp
        operator: in-array
        operands:
            - test
