---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: TestEmailforApproval
flagType: string
description: Creating a flag to test email for approval
labels:

availableValues:

isPermanent: false
